before_script:
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - echo $SSH_PUBLIC_KEY > ~/.ssh/id_rsa.pub
    - ssh-keyscan -H -t rsa github.com >> ~/.ssh/known_hosts
    - chmod 400 ~/.ssh/id_rsa

stages:
    - deploy

mirror:
    stage: deploy
    script:
        - git push --tag "git@github.com:chancefocus/tensorflow.git" $CI_COMMIT_REF_NAME
    only:
        - tags
